### ISSUE TITLE
Add autocompletion in places where it's needed

### ISSUE THREAD

**Issue by KowalskiPiotr98** [rinkudesu/rinkudesu-webui#70]
- [x] #111

~~- [ ] Add support for back-end pagination in links (https://github.com/rinkudesu/rinkudesu-links/issues/47) and tags (https://github.com/rinkudesu/rinkudesu-tags/issues/93)~~ apparently Tomselect does not support dynamic loading of items on scroll, so for now we'll just load all of them.
- [x] https://github.com/rinkudesu/rinkudesu-tags/issues/94
- [x] Finalize tag assignment from #64 so that you can just enter name.
- [x] This should also follow-up on #65 as autocompletion is necessary for multi-selectable tags.
